name: AF agent workflow
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: af_agent
  TEST_CMD: pytest -q   
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: docker build
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meata
        uses: docker/metadata-action@v5
        with:
          images:  ${{ env.IMAGE_NAME }}
          tags: | 
            type=raw,value=sha-${{ github.sha }}
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build (for tests)
        uses: docker/build-push-action@v6
        with:
          load: true
          context: .
          file: ./Dockerfile
          tags: ${{ env.IMAGE_NAME }}:test
          build-args: |
            GIT_SHA=${{ github.sha }}
            BUILD_DATE=${{ steps.meta.outputs.created }} 

      - name: Run tests inside container
        run: |
          docker run --rm \
            -e CI=true \
            ${{ env.IMAGE_NAME }}:test \
            bash -lc "${TEST_CMD}"

      - name: Log in to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: 

       


